version: '2'
services:

  uwsgi:
    build: .
    links:
      - db
    command: ./uwsgi.sh
#    ports:
#      - "5000:5000"
    volumes:
      - /static
      - ./spcommerce/media:/media
    depends_on:
      - db

  db:
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data

  nginx:
    build: ./nginx 
    links:
      - uwsgi
    volumes_from:
      - uwsgi
    ports:
      - "8000:80"
    depends_on:
      - uwsgi
