version: '2'
services:

  db:
    restart: always
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./var/pg-data:/var/lib/postgresql/data

  web:
    restart: always
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./var/www-data:/code
    links:
      - db
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web

