# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='exp_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
