# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160604_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
