# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160614_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
