# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0002_remove_basketitem_category'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('card_id', models.CharField(max_length=100, null=True)),
                ('shipping_nickname', models.CharField(max_length=100, null=True)),
                ('shipping_first_name', models.CharField(max_length=100, null=True)),
                ('shipping_last_name', models.CharField(max_length=100, null=True)),
                ('shipping_address1', models.CharField(max_length=100, null=True)),
                ('shipping_address2', models.CharField(max_length=100, null=True)),
                ('shipping_city', models.CharField(max_length=100, null=True)),
                ('shipping_state', models.CharField(max_length=100, null=True)),
                ('shipping_zip', models.CharField(max_length=16, null=True)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_phone_number', models.CharField(max_length=16, null=True)),
                ('billing_address1', models.CharField(max_length=100, null=True)),
                ('billing_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_city', models.CharField(max_length=100, null=True)),
                ('billing_state', models.CharField(max_length=50, null=True)),
                ('billing_zip', models.CharField(max_length=16, null=True)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('cc_four', models.CharField(blank=True, max_length=4, null=True)),
                ('brand', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
